[build]
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	baseUrl = "https://machodiscordpackage.cf"

	sitemapPath = "/sitemap.xml"

	ignorePeriod = 0

	providers = [
		"google",
		"yandex"
	]